markdown: kramdown
exclude: [node_modules, bower_components, vendor]
url: https://suricate-io.github.io
kramdown:
  input: GFM
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
