version: "2.1"
services:
  site:
    container_name: suricate-io.github.io
    command: jekyll serve -w --host 0.0.0.0
    image: jekyll/jekyll:latest
    volumes:
      - ./:/srv/jekyll
      # this volume will keep all gems
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
